// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import RemoveClassController from "./remove_class_controller"
application.register("remove-class", RemoveClassController)

import SubmitTransactionController from "./submit_transaction_controller"
application.register("submit-transaction", SubmitTransactionController)

import ToggleClassController from "./toggle_class_controller"
application.register("toggle-class", ToggleClassController)

import TransactionsController from "./transactions_controller"
application.register("transactions", TransactionsController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
import UpdateModalController from "./update_modal_controller"
application.register("update-modal", UpdateModalController)
