version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/myplace"
    ports:
      - "3000:3000"
    depends_on:
      - postgres

    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SCHEMA: postgres
      DB_HOST: postgres
