# version: '3.7'
# services:
#   postgres:
#     image: postgres
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     expose:
#       - 5432

#   app:
#     build: .
#     command: bundle exec rails s -p 3000 -b '0.0.0.0'
#     volumes:
#       - ".:/myplace"
#     ports:
#       - "3000:3000"
#     depends_on:
#       - postgres

#     environment:
#       DB_USER: postgres
#       DB_PASSWORD: postgres
#       DB_SCHEMA: postgres
#       DB_HOST: postgres


version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    volumes:
      - './:/src'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local
